// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcn6l29BSWYREiuRZveUAXKIkYpvOw4xU',
    appId: '1:220470942153:web:96d92f9f90a7feb2aeb018',
    messagingSenderId: '220470942153',
    projectId: 'omaapp-bf53e',
    authDomain: 'omaapp-bf53e.firebaseapp.com',
    storageBucket: 'omaapp-bf53e.firebasestorage.app',
    measurementId: 'G-TE4ZS9HBRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdDMpNhPmiI5p7BTTQJAWcQ6USgfoggUk',
    appId: '1:220470942153:android:4b7a6bbd0fd14f21aeb018',
    messagingSenderId: '220470942153',
    projectId: 'omaapp-bf53e',
    storageBucket: 'omaapp-bf53e.firebasestorage.app',
  );
}
